version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bd_nicolas_guarin_clan8
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

    ports:
      - "5555:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
